DB_CONN_STRING: 192.168.1.39:1521/orcl
DB_ENCODING: UTF-8
DB_USER_NAME: hr
DB_USER_PASSWORD: ENC_gAAAAABeFmR9ER3DJsqpOOuaAzdaHLsdJZJcNT0Sbs6T1Vgk6ZRwa-R6CuKZpuXVEVxTaF5czEDywda9e3XUTQGAVRtM7KVhTQ==
SK: aTdaekd6S20wdjgxOHlwLWd2X09TS0lrUFRNVkJIcnNIVzczWWo5TGE4RT0=
