CURRENT_SCHEMA: hr
DB_CONN_STRING: 192.168.1.41:1521/orcl
DB_ENCODING: UTF-8
DB_EXECUTE_TIMEOUT: 10000
DB_USER_NAME: hr
DB_USER_PASSWORD: ENC_gAAAAABeJEx4rXZZFlamknzcsk24tRgRf8zb9mU8GFevZu1EIQrZz4pyrpVjbVg1yJw59O0-pvJRmOtarJjQf4LgsKzN0neFAA==
SK: VWtyUURrTzdBa0lqb0FJdTRxdlg0VlpJeVp4ZEJEbmVDX0I2SFVDcG5mbz0=
