# WS http path = <host>:<port>/<url>
# port set up into nginx config file
URL : 'template'

# LOG_LEVEL 20 -- production , 10 -- debug
LOG_LEVEL : 20

# get data SQL
SQL_GET : >
  SELECT 'Hello1' as parm1, 'World1' as parm2 FROM DUAL
  where
    1 = :inp1
  union all
  SELECT 'Hello2' as parm1, 'World2' as parm2 FROM DUAL
  where
    2 = :inp2

# Max rows for result. It depends on server's memory size.
MAX_FETCH_ROWS : 1000

# WS documentation and swagger file http path <host>:<port>/<url>/swagger
SPECIFICATIONS:
  SERVICE_DESCRITION:
    TITLE: "Processing system API"
    DESCRITION: "Template get service "
    VERSION: "2020_01_01"
  GET_DESCRITION:
    DESCRITION: "Get couple rows from dual"
    INPUT_REQUIRED_FIELDS:
      inp1: "inp1 descr - Set '1' for successful get "
      inp2: "inp2 descr - Set '2' for successful get "
    RESPONCE_FIELDS:
      parm1: "parm1 descr"
      parm2: "parm2 descr"

# WS status check http path <host>:<port>/<url>/status
statDepts: 5 # statistics depth in minutes