# https://loguru.readthedocs.io/en/stable/api/logger.html#file
loguruconf:
  handlers :
    - {
      sink: "./log/+-template-+.log",
      enqueue: True,
      serialize: False,
      rotation: "50 MB",
      retention: 20,
      compression: "zip",
      level: "INFO"
    }
