# WS http path = <host>:<port>/getAuthlist
PORT : 8081
URL : 'getAuthList'

# LOG_LEVEL 20 -- production , 10 -- debug
LOG_LEVEL : 20

# WS status check http path <host>:<port>/getAuthlist/status
statDepts: 5 # statistics depth in minutes

# get data SQL
SQL_GET : >
  select
  d.id as "id",
  to_char(d.trans_date, 'yyyymmddHHMiss') as "transactionDate",
  d.TRANS_TYPE as "transTypeId",
  xwdoc('TRANS_TYPE', d.TRANS_TYPE) as "transType",
  d.posting_status as "transactionStatus",
  ar.trans_amount as "transactionAmount",
  xwdoc('TRANS_CURR',ar.trans_curr) as "transactionCurrency",
  abs(ar.BASE_AMOUNT) as "amountInAccCurr",
  xwdoc('TRANS_CURR',acn.curr) as "acctCurr",
  glob.GET_TAG_VALUE(d.add_info, 'EXT_FEE_AMOUNT') as "feeAmount",
  glob.GET_TAG_VALUE(d.add_info, 'EXT_FEE_CURR') as "feeCurrency",
  xwdoc('REQUEST_CATEGORY',d.request_category) as "requestCategory",
  glob.GET_TAG_VALUE(d.add_info, 'WSP_DEV_TYPE') as "tokenDeviceType",
  glob.GET_TAG_VALUE( d.add_info, 'MC_WALLET_DATA') as "tokenProvider",
  d.source_channel as "sourceChannel",
  d.target_channel as "targetChannel",
  d.add_info as "addInfo",
  ar.trans_details as "transactionDescription" ,
  ar.ret_ref_number as "retrievalRefNumber" ,
  ar.auth_code as "authCode",
  ar.trans_city as "transCity" ,
  ar.trans_country as "transCountry",
  ar.sic_code as "mccCategory",
  xwdoc('TRANS_COND_ATTR',d.trans_cond_attr) as "transCondAttr",
  substr(d.target_number,0,4)||'***'||substr(d.target_number,-4,4) as "contractFor"
  from acnt_contract acn
    inner join AUTH_RECORD ar
      on ar.ACNT_CONTRACT__OID = acn.id
    and ar.CREDIT_STATUS = 'A'
    and ar.id is not null
    and ar.RETURN_CODE = 0
    and ar.trans_date > sysdate - 60
    and ar.POSTING_DATE > sysdate - 60
    and ar.CREDIT_TYPE in ('P', 'U', 'A', 'C', 'c', 'W', 'w', 'F', 'Z', 'T', 'X')
    inner join doc d on d.id = ar.doc__id
    and d.amnd_state = 'A'
    and d.is_authorization = 'Y'
  where acn.amnd_state = 'A'
  and acn.CONTRACT_NUMBER = :mainContractNumber

# Max rows for result. It depends on server's memory size.
MAX_FETCH_ROWS : 1000

# WS documentation http path <host>:<port>/getAuthlist/swagger and <host>:<port>/getAuthlist/swagger.json
SPECIFICATIONS:
  VERSION: "V1"
  SERVICE_DESCRITION:
    TITLE: "WAY4 CARDS API"
    DESCRITION: "Get active auth transaction list for client's cards by main contract number"
    RELEASE: "2020_01_21"
  GET_DESCRITION:
    DESCRITION: "Get active auth transaction list for client's cards by main contract number"
    INPUT_REQUIRED_FIELDS:
      mainContractNumber: "Main contract number"
    RESPONCE_FIELDS:
      id: "way4 unique document number"
      transactionDate: "local transaction date time - yyyymmddHHMiss"
      transTypeId: "trans type unique Id"
      transType: "trans type name"
      transactionStatus: "transaction processing status"
      transactionAmount: "transaction amount"
      transactionCurrency: "transaction currency"
      amountInAccCurr: "transaction amount in account currency"
      acctCurr: "account currency"
      feeAmount: "fee amount"
      feeCurrency: "fee currency"
      requestCategory: "request category (request/advice/reverse)"
      tokenDeviceType: "token acceptance device type Phone/Tablet/Watch"
      tokenProvider: "token provider"
      sourceChannel: "source channel"
      targetChannel: "target channel"
      addInfo: "some tag=value; add info"
      transactionDescription: "transaction description"
      retrievalRefNumber: "retrieval ref number - printed on receipt"
      authCode: "auth code - printed on receipt"
      transCity: "transaction city"
      transCountry: "trans country"
      mccCategory: "mccCategory"
      transCondAttr: "tag; format transaction attributes (chip, attended , etc)"
      contractFor: "card number masked 4***4"

#allowed only if in list - can be removed
ASSERTIONS_PARMS:
  GET: # REST method name
    source_system:
      - 'DBO'
      - 'DIASOFT'
      - 'ESB'

ASSERTIONS_FORMATS:
  GET:
    inp2: 're=[0-9,a-z,A-Z]+'